SELECT 
    COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE AS SPECIES,
    SUM(COUNCIL.COMPREHENSIVE_BLEND_CA.WEIGHT_POSTED)AS TONS,
    to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM') AS MONTH_WED,
    COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR AS GEAR, 
    COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR AS YEAR, 
    COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE AS AREA,
    COUNCIL.COMPREHENSIVE_BLEND_CA.ADFG_STAT_AREA_CODE AS ADFG_AREA,
    'DOMESTIC' AS SOURCE 
FROM COUNCIL.COMPREHENSIVE_BLEND_CA 
WHERE  COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE
         -- insert area 
      AND COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR 
         -- insert eyears
    AND COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR 
         -- insert syears
      AND COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE 
         -- insert species_catch
GROUP BY 
      COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
      to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM'), 
      COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR,
      COUNCIL.COMPREHENSIVE_BLEND_CA.ADFG_STAT_AREA_CODE
ORDER BY
      COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
      to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM'), 
      COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR
